name: yuix
description: Simple GoRouter Alternative & more
version: 2.2.2
homepage: https://github.com/rbdog/yuix

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cron: ^0.5.0
  intl: ^0.17.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  jose: ^0.3.2
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
